import Head from "next/head";
import Image from "next/image";
import Header from "../components/header/header";
import Section1 from "../components/section1/index";
import Section2 from "../components/section2/index";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Header />
          <Section1 />
        </div>
        <Section2 />
      </main>

      <div className={styles.footer}></div>
    </div>
  );
}
